---
jupyter:
  jupytext:
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.0'
      jupytext_version: 0.8.1
  kernelspec:
    display_name: Python 3
    language: python
    name: python3
  language_info:
    codemirror_mode:
      name: ipython
      version: 3
    file_extension: .py
    mimetype: text/x-python
    name: python
    nbconvert_exporter: python
    pygments_lexer: ipython3
    version: 3.6.5
---

# Four dimensional images

For this notebook you will need:

* [ds114 FMRI image]({{ site.url }}{{ site.baseurl }}/data/ds114_sub009_t2r1.nii).

```{python}
# Our usual set-up
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
# Set 'gray' as the default colormap
plt.rcParams['image.cmap'] = 'gray'
# Display array values to 4 digits of precision
np.set_printoptions(precision=4, suppress=True)
```

We now leave our three-dimensional comfort zone.

Images can also be four-dimensional. It’s easiest to think of four dimensional
images as a stack of 3-dimensional images (volumes).

Here we load a four dimensional image. It is an functional MRI image, where
the volumes are collected in sequence a few seconds apart.

```{python}
import nibabel as nib
```

```{python}
img = nib.load('ds114_sub009_t2r1.nii')
data = img.get_data()
```

The image we have just loaded is a four-dimensional image, with a
four-dimensional array:

```{python}
data.shape
```

The first three axes represent three dimensional space. The last axis
represents time. Here the last (time) axis has length 173. This means that,
for each of these 173 elements, there is one whole three dimensional image. We
often call the three-dimensional images volumes. So we could say that this 4D
image contains 173 volumes.

We have previously been taking slices over the third axis of a
three-dimensional image. We can now take slices over the fourth axis of this
four-dimensional image:

```{python}
first_vol = data[:, :, :, 0]  # A slice over the final (time) axis
```

This slice selects the first three-dimensional volume (3D image) from the 4D array:

```{python}
first_vol.shape
```

`first_vol` is a 3D image just like the 3D images you have already seen:


```{python}
# A slice over the third dimension of a 3D image
plt.imshow(first_vol[:, :, 14])
```

We can now start to look at how the signal changes over time.  To begin, we do
something very simple, which is to take the mean of all the voxel values in
each 3D scan:

```{python}
means = []
n_vols = data.shape[-1]  # The length of the last axis
for i in range(n_vols):
    this_vol = data[:, :, :, i]
    mean = np.mean(this_vol)  # Mean across all voxels
    means.append(mean)
```

```{python}
plt.plot(means)
```

Ouch - the first scan has a much higher mean than the others.  Why?

```{python}
plt.imshow(first_vol[:, :, 14])
```

```{python}
second_vol = data[:, :, :, 1]
plt.imshow(second_vol[:, :, 14])
```

```{python}
vol_diff = first_vol - second_vol
plt.imshow(vol_diff[:, :, 14])
```
