# What is an image?

In this page we explore the nature of NIfTI images.

First we load an example image to see if we can understand the image data.

Download the image from <{{ site.url }}{{ site.baseurl }}/data/ds114_sub009_highres.nii>.

```{python}
# This is a Python module
import os  # module for interacting with the operating system
```

If you want to explore modules or objects, type their name followed by a
period, and press tab to see what functions or classes are available.

The image we are going to explore should be the same directory as this
exercise.

```{python}
# Get the current working directory (CWD)
cwd = os.getcwd()
print(cwd)
```

```{python}
# List files and directories in the current working directory
print(os.listdir(cwd))
```

Read the image into memory.

```{python}
# Open a file in Read Binary mode
fobj = open('ds114_sub009_highres.nii', 'rb')
print(fobj)
```

```{python}
# read all the characters into a variable in memory
contents = fobj.read()
```

Show the `type` of object is attached to this variable called `contents`:

```{python}
type(contents)
```

How big is this file in terms of bytes?

```{python}
n_bytes = len(contents)
n_bytes
```

If 1 mebibyte (MiB) (http://en.wikipedia.org/wiki/Megabyte) is size 1024 \*
1024, what is the file size in MiB?

```{python}
n_mib = n_bytes / (1024 * 1024)
n_mib
```

This is a [NIfTI1 format](http://nifti.nimh.nih.gov/nifti-1) file.  That means
that the first 352 bytes contains the "header" that describes the parameters
of the image and the data following.

We want to print out the contents of the first 352 bytes of `contents`
to have a look at it.

To do this, we are going to need *string slicing* to get the first 352
bytes:

```{python}
print(contents[:352])
```

Which software wrote this image?

Here is the format of the NIfTI1 header :
<http://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields>

We are now going to try and work out the `datatype` of this image.  This is
stored in the `datatype` field of the header. Careful - there is also a
`data_type` field (with an underscore), which we will ignore.

Looking at the web page above, how many bytes is the `datatype` value
stored in?

How would you get the bytes in `contents` that contain the `datatype`
value?  We need slicing again, and the information from `Byte offset` column
in the NIfTI1 header page above:

```{python}
data_type_chars = contents[70:72]
```

The `datatype` value is stored in binary form (rather than text form).  The
value for `datatype` is stored in the header in the same format that the
computer stores the number in memory. We want to convert this binary format to
a number that Python understands. To do that, we use the [struct module] (https://docs.python.org/2/library/struct.html)

```{python}
import struct
```

We are going to use the `struct.unpack` function. Open a new cell below this
one with `b` and type `struct.unpack?` followed by Shift-Return to see the
help for this function.

Now we have read the help, we know we need two things. The first is a
string that give the code for the binary format of the data. This is the
"format string". The second is the string containing the bytes of the
data.

We first need to specify the format of the character data. Have a look
at the [help on format
strings](https://docs.python.org/2/library/struct.html#format-characters) in
the Python documentation and the NIfTI web page above.

Here is the format specifier for our value:

```{python}
fmt_specifier = 'h'  # Why? (check the web pages above)
```

Now we read the datatype value into a number that Python understands:

```{python}
datatype = struct.unpack(fmt_specifier, data_type_chars)
print(datatype)
```

This is a numerical *code* for a data type. To see what type this is, see:
<http://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields\_pages/datatype.html>

We could continue reading the NIfTI header in the same way, but luckily
someone has done that work for us. Enter the `nibabel` package:

```{python}
import nibabel
```

For now, we will use this package without worrying much about how it works.
Have a look to see what `nibabel` can do by opening up a new cell with `b` and
typing `nibabel?` and `nibabel.` followed by Tab.

As with most Python packages, you can check what version of nibabel you have
by printing the `__version__` variable of the package:

```{python}
print(nibabel.__version__)
```

If you have a nibabel version below 2.0.0, please let your instructor know so
they can fix that.

You can load an image into memory like this:

```{python}
img = nibabel.load('ds114_sub009_highres.nii')
```

Let's have a look at the header:

```{python}
print(img.header)  # doctest: +SKIP
```

As you can see, nibabel has worked out the datatype for us.
